pipeline:
  name: exam-app-backend
  identifier: examappbackend
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harnessgitconnector
        repoName: examportal-feature-flag-backend
        build: <+input>
  stages:
    - stage:
        name: clone
        identifier: clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: awsconnector
                    region: us-east-1
                    account: "860602188711"
                    imageName: examportal-backend
                    tags:
                      - latest
                    caching: true
