version: '3'

services:
  exam-mysql:
    image: mysql:latest
    container_name: exam-mysql
    environment:
      MYSQL_HOST: exam-mysql
      MYSQL_ROOT_PASSWORD: abc
      MYSQL_DATABASE: exam
      MYSQL_USER: exam-user
      MYSQL_PASSWORD: abc
      MYSQL_PORT: 3307
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  exam-app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8880:8080"
    command: mvn clean spring-boot:run
    depends_on:
    - exam-mysql

volumes:
  dbdata: