apiVersion: v1
kind: Service
metadata:
  labels:
    app: examp-app
  name: examp-app
spec:
  ports:
  - name: exam-app
    port: 8880
    protocol: TCP
    targetPort: 8888
  selector:
    app: examp-app
  type: NodePort
status:
  loadBalancer: {}
